server: 
  port: 9001
spring: 
  application: 
    name: bordereaux-service
  datasource: 
    driverClassName: oracle.jdbc.OracleDriver
    username: BASE_BORD
    password: BASE_BORD
    url: jdbc:oracle:thin:@localhost:1521:orcl
                   
  jpa:
    hibernate:
      ddlAuto: create-drop
      dialect: org.hibernate.dialect.Oracle10gDialect
    
      
      
security:
  basic:
    enabled: false
  user:
    name: root
    password: root
Access-Control-Allow-Credentials: true

Access-Control-Allow-Origin: http://localhost:4200

Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE

Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
