server: 
  port: 9001
spring: 
  application: 
    name: bordereaux-service
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/over
   
  jpa:
    hibernate:
      ddlAuto: create-drop
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false
      
      
security:
  basic:
    enabled: false
  user:
    name: root
    password: root
Access-Control-Allow-Credentials: true

Access-Control-Allow-Origin: http://localhost:4200

Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE

Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
