    
server: 
  port: 9001
  
spring: 
  application: 
    name: users-management-service

  data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/file-storageTT
      mongo.repositories.enabled: true 
   
   http:
      multipart:
       max-file-size: 1048576KB
       max-request-size: 1048576KB
       
       
security:
  basic:
    enabled: false
  user:
    name: user
    password: user
